version: '3.1'

services:
  database:
    image: postgres:latest
    container_name: go-hotel-db 
    env_file:
      - ./app.env
    ports:
      - 5432:5432
    volumes:
      - database:/var/lib/postgresql/data
    networks:
      - api-service

  # app:
  #   container_name: go-hotel-app
  #   build: .
  #   ports:
  #     - 8080:8080
  #   restart: on-failure
  #   volumes:
  #     - api:/usr/src/app/
  #   depends_on:
  #     - database
  
  
    
  
volumes:
  api:
  database:

# Networks to be created to facilitate communication between containers
networks:
  api-service:
    driver: bridge   
